name: Development pipeline by Lxb1628 Fork

on:
  push:
    branches:
      - "*"
      - "!feature/"
    tags-ignore:
      - '**'

jobs:
  release:
    name: Publish development build to CDN
    runs-on: ubuntu-latest
    env:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Workaround checkout issues
        run: |
          git fetch --tags --force
      - name: Create Package
        uses: BigWigsMods/packager@v2
        with:
          args: -n "{package-name}-$GITHUB_REF_NAME-{project-version}"
      - name: Get package name
        run: |
          echo "PACKAGE=$(find .release -type f -name *.zip -printf "%f\n")" >> $GITHUB_ENV
